### ISSUE TITLE
Revisit .eslintrc.js workarounds for eslint-scanjs-rules

### ISSUE THREAD

**Issue by jseppi** [cloud-gov/pages-core#1173]
CodeClimate [now has the `eslint-plugin-scanjs-rules`](https://github.com/codeclimate/codeclimate-eslint/pull/307), so we should be able to get rid of the weird conditional inclusion of them in our `.eslintrc.js` files here and in `federalist-builder`. 🎉

**Comment by jseppi** [comment]
Bleh, gave this shot but couldn't get it working with CodeClimate.

Our Before You Ship guide now alternatively (?) recommends `eslint-config-nodesecurity`, which CodeClimate also supports, but I had trouble getting that working with its recommended config. CodeClimate reported this error:

```
/usr/src/app/lib/validate_config.js:17
        throw e;
        ^

TypeError: Cannot read property 'recommended' of undefined
Referenced from: /code/.eslintrc.js
    at loadConfigFile (/usr/local/node_modules/eslint/lib/config/config-file.js:217:40)
    at load (/usr/local/node_modules/eslint/lib/config/config-file.js:535:18)
    at configExtends.reduceRight.e (/usr/local/node_modules/eslint/lib/config/config-file.js:424:36)
    at Array.reduceRight (native)
    at applyExtends (/usr/local/node_modules/eslint/lib/config/config-file.js:408:28)
    at Object.load (/usr/local/node_modules/eslint/lib/config/config-file.js:566:22)
    at loadConfig (/usr/local/node_modules/eslint/lib/config.js:63:33)
    at getLocalConfig (/usr/local/node_modules/eslint/lib/config.js:130:29)
    at Config.getConfig (/usr/local/node_modules/eslint/lib/config.js:260:26)
    at Config.getConfig (/usr/src/app/lib/eslint-patch.js:45:46)
```

I don't think it's worth it to spend more time on this right now, so recommend punting on it a while longer.

**Comment by jseppi** [comment]
IceBoxing

**Comment by apburnes** [comment]
No more Code Climate.
